[[redirects]]
  from = "/nba"
  to = "/nba/index.html"
  status = 200

[[redirects]]
  from = "/nba/"
  to = "/nba/index.html"
  status = 200

[[redirects]]
  from = "/infinite"
  to = "/infinite/index.html"
  status = 200

[[redirects]]
  from = "/infinite/"
  to = "/infinite/index.html"
  status = 200
